// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCleanerSettings() {
  return window['go']['main']['App']['GetCleanerSettings']();
}

export function GetDirSize(arg1) {
  return window['go']['main']['App']['GetDirSize'](arg1);
}

export function GetSyncConfig() {
  return window['go']['main']['App']['GetSyncConfig']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function HashFile(arg1, arg2) {
  return window['go']['main']['App']['HashFile'](arg1, arg2);
}

export function HashText(arg1, arg2) {
  return window['go']['main']['App']['HashText'](arg1, arg2);
}

export function IsCleanRunning() {
  return window['go']['main']['App']['IsCleanRunning']();
}

export function IsSyncRunning() {
  return window['go']['main']['App']['IsSyncRunning']();
}

export function PreviewClean(arg1) {
  return window['go']['main']['App']['PreviewClean'](arg1);
}

export function PreviewSync(arg1) {
  return window['go']['main']['App']['PreviewSync'](arg1);
}

export function ResolveSyncConflict(arg1) {
  return window['go']['main']['App']['ResolveSyncConflict'](arg1);
}

export function SaveCleanerSettings(arg1) {
  return window['go']['main']['App']['SaveCleanerSettings'](arg1);
}

export function SaveSyncConfig(arg1) {
  return window['go']['main']['App']['SaveSyncConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartClean(arg1) {
  return window['go']['main']['App']['StartClean'](arg1);
}

export function StartSync(arg1) {
  return window['go']['main']['App']['StartSync'](arg1);
}

export function StopClean() {
  return window['go']['main']['App']['StopClean']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
