// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastEnvChange() {
  return window['go']['main']['App']['BroadcastEnvChange']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteEnv(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnv'](arg1, arg2);
}

export function ExportEnvFile(arg1, arg2) {
  return window['go']['main']['App']['ExportEnvFile'](arg1, arg2);
}

export function GetApiConfig() {
  return window['go']['main']['App']['GetApiConfig']();
}

export function GetCleanerSettings() {
  return window['go']['main']['App']['GetCleanerSettings']();
}

export function GetDirSize(arg1) {
  return window['go']['main']['App']['GetDirSize'](arg1);
}

export function GetEnv(arg1, arg2) {
  return window['go']['main']['App']['GetEnv'](arg1, arg2);
}

export function GetFTPLogs(arg1) {
  return window['go']['main']['App']['GetFTPLogs'](arg1);
}

export function GetFTPStatus() {
  return window['go']['main']['App']['GetFTPStatus']();
}

export function GetFtpConfig() {
  return window['go']['main']['App']['GetFtpConfig']();
}

export function GetHighRiskVariables() {
  return window['go']['main']['App']['GetHighRiskVariables']();
}

export function GetLocalServerConfig() {
  return window['go']['main']['App']['GetLocalServerConfig']();
}

export function GetPortViewerPrefs() {
  return window['go']['main']['App']['GetPortViewerPrefs']();
}

export function GetSFTPStatus() {
  return window['go']['main']['App']['GetSFTPStatus']();
}

export function GetServerLogs(arg1) {
  return window['go']['main']['App']['GetServerLogs'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSftpConfig() {
  return window['go']['main']['App']['GetSftpConfig']();
}

export function GetSyncConfig() {
  return window['go']['main']['App']['GetSyncConfig']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function HashFile(arg1, arg2) {
  return window['go']['main']['App']['HashFile'](arg1, arg2);
}

export function HashText(arg1, arg2) {
  return window['go']['main']['App']['HashText'](arg1, arg2);
}

export function ImportEnvFileCommit(arg1) {
  return window['go']['main']['App']['ImportEnvFileCommit'](arg1);
}

export function ImportEnvFilePreview(arg1, arg2) {
  return window['go']['main']['App']['ImportEnvFilePreview'](arg1, arg2);
}

export function IsCleanRunning() {
  return window['go']['main']['App']['IsCleanRunning']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function IsPortElevated() {
  return window['go']['main']['App']['IsPortElevated']();
}

export function IsSyncRunning() {
  return window['go']['main']['App']['IsSyncRunning']();
}

export function KillPortProcess(arg1) {
  return window['go']['main']['App']['KillPortProcess'](arg1);
}

export function KillPortProcesses(arg1) {
  return window['go']['main']['App']['KillPortProcesses'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListEnv(arg1) {
  return window['go']['main']['App']['ListEnv'](arg1);
}

export function ListLanAddresses() {
  return window['go']['main']['App']['ListLanAddresses']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListServerFiles(arg1) {
  return window['go']['main']['App']['ListServerFiles'](arg1);
}

export function LoadBackup(arg1) {
  return window['go']['main']['App']['LoadBackup'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function ParseAllPathSegments() {
  return window['go']['main']['App']['ParseAllPathSegments']();
}

export function ParsePath(arg1) {
  return window['go']['main']['App']['ParsePath'](arg1);
}

export function PreviewClean(arg1) {
  return window['go']['main']['App']['PreviewClean'](arg1);
}

export function PreviewSync(arg1) {
  return window['go']['main']['App']['PreviewSync'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function ResolveSyncConflict(arg1) {
  return window['go']['main']['App']['ResolveSyncConflict'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveApiConfig(arg1) {
  return window['go']['main']['App']['SaveApiConfig'](arg1);
}

export function SaveCleanerSettings(arg1) {
  return window['go']['main']['App']['SaveCleanerSettings'](arg1);
}

export function SaveEnvBatch(arg1) {
  return window['go']['main']['App']['SaveEnvBatch'](arg1);
}

export function SaveFtpConfig(arg1) {
  return window['go']['main']['App']['SaveFtpConfig'](arg1);
}

export function SaveLocalServerConfig(arg1) {
  return window['go']['main']['App']['SaveLocalServerConfig'](arg1);
}

export function SavePath(arg1) {
  return window['go']['main']['App']['SavePath'](arg1);
}

export function SavePortViewerPrefs(arg1) {
  return window['go']['main']['App']['SavePortViewerPrefs'](arg1);
}

export function SaveSftpConfig(arg1) {
  return window['go']['main']['App']['SaveSftpConfig'](arg1);
}

export function SaveSyncConfig(arg1) {
  return window['go']['main']['App']['SaveSyncConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SendHttpRequest(arg1) {
  return window['go']['main']['App']['SendHttpRequest'](arg1);
}

export function SetEnv(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetEnv'](arg1, arg2, arg3, arg4);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Snapshot(arg1) {
  return window['go']['main']['App']['Snapshot'](arg1);
}

export function StartClean(arg1) {
  return window['go']['main']['App']['StartClean'](arg1);
}

export function StartFTP(arg1) {
  return window['go']['main']['App']['StartFTP'](arg1);
}

export function StartSFTP(arg1) {
  return window['go']['main']['App']['StartSFTP'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StartSync(arg1) {
  return window['go']['main']['App']['StartSync'](arg1);
}

export function StopClean() {
  return window['go']['main']['App']['StopClean']();
}

export function StopFTP() {
  return window['go']['main']['App']['StopFTP']();
}

export function StopSFTP() {
  return window['go']['main']['App']['StopSFTP']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
