// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {envreg} from '../models';
import {apidebug} from '../models';
import {cleaner} from '../models';
import {ftpserver} from '../models';
import {httpserver} from '../models';
import {main} from '../models';
import {syncer} from '../models';
import {procutil} from '../models';

export function BroadcastEnvChange():Promise<envreg.OperationResult>;

export function DeleteBackup(arg1:string):Promise<envreg.OperationResult>;

export function DeleteEnv(arg1:string,arg2:string):Promise<envreg.BatchSaveResult>;

export function ExportEnvFile(arg1:string,arg2:string):Promise<envreg.OperationResult>;

export function GetApiConfig():Promise<apidebug.ApiGlobalConfig>;

export function GetCleanerSettings():Promise<cleaner.Settings>;

export function GetDirSize(arg1:string):Promise<number>;

export function GetEnv(arg1:string,arg2:string):Promise<envreg.EnvEntry>;

export function GetFTPLogs(arg1:number):Promise<Array<ftpserver.LogEntry>>;

export function GetFTPStatus():Promise<ftpserver.Status>;

export function GetFtpConfig():Promise<ftpserver.Config>;

export function GetHighRiskVariables():Promise<Array<string>>;

export function GetLocalServerConfig():Promise<httpserver.Config>;

export function GetPortViewerPrefs():Promise<main.PortViewerPrefs>;

export function GetSFTPStatus():Promise<ftpserver.SFTPStatus>;

export function GetServerLogs(arg1:number):Promise<Array<httpserver.LogEntry>>;

export function GetServerStatus():Promise<httpserver.ServerStatus>;

export function GetSftpConfig():Promise<ftpserver.SFTPConfig>;

export function GetSyncConfig():Promise<syncer.Config>;

export function GetTheme():Promise<string>;

export function HashFile(arg1:string,arg2:string):Promise<string>;

export function HashText(arg1:string,arg2:string):Promise<string>;

export function ImportEnvFileCommit(arg1:envreg.ImportPreview):Promise<envreg.BatchSaveResult>;

export function ImportEnvFilePreview(arg1:string,arg2:string):Promise<envreg.ImportPreview>;

export function IsCleanRunning():Promise<boolean>;

export function IsElevated():Promise<boolean>;

export function IsPortElevated():Promise<boolean>;

export function IsSyncRunning():Promise<boolean>;

export function KillPortProcess(arg1:number):Promise<void>;

export function KillPortProcesses(arg1:Array<number>):Promise<void>;

export function ListBackups():Promise<Array<envreg.BackupMeta>>;

export function ListEnv(arg1:string):Promise<Array<envreg.EnvEntry>>;

export function ListLanAddresses():Promise<Array<string>>;

export function ListPorts():Promise<Array<procutil.PortEntryWithProc>>;

export function ListServerFiles(arg1:string):Promise<Array<httpserver.FileItem>>;

export function LoadBackup(arg1:string):Promise<envreg.BackupSnapshot>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ParseAllPathSegments():Promise<Array<envreg.PathSegment>>;

export function ParsePath(arg1:string):Promise<Array<envreg.PathSegment>>;

export function PreviewClean(arg1:cleaner.Settings):Promise<Array<cleaner.PreviewItem>>;

export function PreviewSync(arg1:syncer.Config):Promise<Array<syncer.PreviewItem>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ResolveSyncConflict(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<envreg.BatchSaveResult>;

export function SaveApiConfig(arg1:apidebug.ApiGlobalConfig):Promise<void>;

export function SaveCleanerSettings(arg1:cleaner.Settings):Promise<void>;

export function SaveEnvBatch(arg1:Array<envreg.EnvChange>):Promise<envreg.BatchSaveResult>;

export function SaveFtpConfig(arg1:ftpserver.Config):Promise<void>;

export function SaveLocalServerConfig(arg1:httpserver.Config):Promise<void>;

export function SavePath(arg1:Array<envreg.PathSegment>):Promise<envreg.BatchSaveResult>;

export function SavePortViewerPrefs(arg1:main.PortViewerPrefs):Promise<void>;

export function SaveSftpConfig(arg1:ftpserver.SFTPConfig):Promise<void>;

export function SaveSyncConfig(arg1:syncer.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SendHttpRequest(arg1:apidebug.HttpRequestParams):Promise<apidebug.HttpResponse>;

export function SetEnv(arg1:string,arg2:string,arg3:string,arg4:string):Promise<envreg.BatchSaveResult>;

export function SetTheme(arg1:string):Promise<void>;

export function Snapshot(arg1:string):Promise<envreg.BackupMeta>;

export function StartClean(arg1:cleaner.Settings):Promise<void>;

export function StartFTP(arg1:ftpserver.Config):Promise<void>;

export function StartSFTP(arg1:ftpserver.SFTPConfig):Promise<void>;

export function StartServer(arg1:httpserver.Config):Promise<void>;

export function StartSync(arg1:syncer.Config):Promise<void>;

export function StopClean():Promise<void>;

export function StopFTP():Promise<void>;

export function StopSFTP():Promise<void>;

export function StopServer():Promise<void>;

export function StopSync():Promise<void>;

export function ValidatePath(arg1:Array<string>):Promise<Array<envreg.PathValidation>>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
