// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cleaner} from '../models';

export function GetCleanerSettings():Promise<cleaner.Settings>;

export function GetDirSize(arg1:string):Promise<number>;

export function GetTheme():Promise<string>;

export function IsCleanRunning():Promise<boolean>;

export function PreviewClean(arg1:cleaner.Settings):Promise<Array<cleaner.PreviewItem>>;

export function SaveCleanerSettings(arg1:cleaner.Settings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function StartClean(arg1:cleaner.Settings):Promise<void>;

export function StopClean():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowToggleMaximise():Promise<void>;
